openapi: 3.0.0
info:
  title: Aquarium Website
  description: Aquarium Website API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://aquarium-3d-website-api-production.up.railway.app/api
    description: railway server
paths:
  /fish:
    get:
      tags:
        - Fish
      responses: 
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /plant:
    get:
      tags:
        - Plant
      responses: 
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /auth/signup:
    post:
      tags:
        - Authorisation
      requestBody:
        description: Create new user
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: new user create successfully
  /user/login:
    post:
      tags:
        - Login
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /user:
    get:
      summary: Get user information
      description: Get information about the authenticated user
      tags:
        - User
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          description: Bearer Token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: The user's ID
                  name:
                    type: string
                    description: The user's name
        "401":
          description: Unauthorized
      security:
        - bearerAuth: []
      components:
        securitySchemes:
          bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
